name: Continuous Integration

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]
    tags: [ "*.*.*" ]

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v2.3.3
      with:
        submodules: true

    - name: 🧰 Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.4

    - name: ↪ Set package version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
      with:
        path: clients/TypeScript

    - name: 🔨 Build
      working-directory: clients/TypeScript
      run: |
        yarn install --frozen-lockfile --non-interactive --logevel=error
        yarn generate-schema-types
        yarn build
        yarn lint

    - name: 🔬 Test
      if: matrix.network == 'testnet'
      working-directory: clients/TypeScript
      run: |
        docker run -d --name cardano-node-ogmios -p 1338:1337 -v ${{ runner.temp }}/db-${{ matrix.network }}:/db cardanosolutions/cardano-node-ogmios:${{ github.sha }}-${{ matrix.network }}
        ../../scripts/wait-for-sync.sh 1338 1
        yarn test
        docker stop cardano-node-ogmios
        docker rm cardano-node-ogmios

    - name: 📦 Pack
      run: |
        ./scripts/pack.sh

    - name: 📤 Upload npm packages
      uses: actions/upload-artifact@v2
      with:
        name: cardano-ogmios-clients-ts-packages
        path: |
          packages/prototype/cardano-js-sdk-prototype-${{ steps.package-version.outputs.current-version}}.tgz
